[package]
name = "rot-event"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
serde.workspace = true
serde_json.workspace = true
rot-contracts = { version = "0.1.0", path = "../rot-contracts" }
rot-id = { version = "0.1.0", path = "../rot-id" }
rot-temporal = { version = "0.1.0", path = "../rot-temporal" }
rot-provenance = { version = "0.1.0", path = "../rot-provenance" }
rot-hash = { version = "0.1.0", path = "../rot-hash" }
