[package]
name = "rot-canonical-json"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
serde.workspace = true
serde_json.workspace = true
serde_jcs.workspace = true
rot-contracts = { version = "0.1.0", path = "../rot-contracts" }

[dev-dependencies]
sha2.workspace = true
hex.workspace = true
