[package]
name = "rot-hash"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
sha2.workspace = true
hex.workspace = true
serde.workspace = true
rot-contracts = { version = "0.1.0", path = "../rot-contracts" }
rot-canonical-json = { version = "0.1.0", path = "../rot-canonical-json" }

[dev-dependencies]
serde_json.workspace = true
